name       : tellico
version    : 3.2.3
release    : 8
source     :
    - https://tellico-project.org/files/tellico-3.2.3.tar.xz : f4456eb31f71151b9786fa171531265b421b2de8140e9adbf6bb584862c42952
license    : GPL-2.0
component  : office
summary    : A collection manager for KDE
description: |
    Tellico makes it easy to track your books, videos, music, even your wine and anything else. A simple and intuitive interface shows cover images, groupings, and any detail you want. Grab information from many popular Internet sites, including IMDB.com, Amazon.com, and most libraries.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(libcdio)
    - pkgconfig(libxslt)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - khtml-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkcddb-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
