name       : tellico
version    : 3.1.4
release    : 5
source     :
    - http://tellico-project.org/files/tellico-3.1.4.tar.xz : 8f611e3be8be095de38fe27d76f3ddeae09962c9aec00298031cc3e71eae95f9
license    : GPL-2.0
component  : office
summary    : A collection manager for KDE
description: |
    Tellico makes it easy to track your books, videos, music, even your wine and anything else. A simple and intuitive interface shows cover images, groupings, and any detail you want. Grab information from many popular Internet sites, including IMDB.com, Amazon.com, and most libraries.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(libcdio)
    - pkgconfig(libxslt)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - khtml-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkcddb-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
